# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - deploytoazure1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout
      # id-token: write # Added to provide the ACTIONS_ID_TOKEN_REQUEST_URL env variable

    steps:
      - uses: actions/checkout@v4

      # Log in to Azure so that we can retrieve Key Vault secrets
      - name: Login to Azure for Key Vault
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4183B13DB97145F99E06745FC8237563 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7FADB8C254B742C6A24857C15163815F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_15D539FFE9254E07ABB18A6CF759EAB1 }}

      # Retrieve the VITE_APP_BACKEND_URL secret from Azure Key Vault
      - name: Get secrets from Azure Key Vault
        id: keyvault
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: 'keytest-milestone'
          secrets: 'VITE_APP_BACKEND_URL'

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Use the secret as an environment variable during build so Vite picks it up
      - name: npm install, build, and test
        env:
          VITE_APP_BACKEND_URL: ${{ steps.keyvault.outputs.VITE_APP_BACKEND_URL }}
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read   # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4183B13DB97145F99E06745FC8237563 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7FADB8C254B742C6A24857C15163815F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_15D539FFE9254E07ABB18A6CF759EAB1 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'deploytoazure1'
          slot-name: 'Production'
          package: .
